# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: |
     **/*Tests.csproj
    arguments: '-v n  -f netcoreapp3.1 --configuration release --no-build --no-restore --collect "Code coverage"'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '*.trx'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
- task: PublishBuildArtifacts@1
  inputs:
    #PathtoPublish: '$(Agent.TempDirectory)'
    ArtifactName: 'drop' 
    publishLocation: 'Container'
    
- task: CmdLine@2
  displayName: 'Display environment'
  inputs:
    script: |
      cd ..
      dir /s *.*
      set
